### ISSUE TITLE
Allow to combine recipes (e.g. CatchAll with RTDC)

### ISSUE THREAD

**Issue by paulmueller** [GuckLab/MPL-Data-Cast#11]
...because you still would like to keep additional files from your measurement.

**Comment by paulmueller** [comment]
@B-Hartmann the idea behind MPLDC is to only process **raw** data from a certain measurement device. In principle I think it does not make sense to combine recipes. However, I think an option "copy other data as well" would be ok. Can you describe again your use case for this, please?

**Comment by B-Hartmann** [comment]
One use case where I would have not only .rtdc files would be if I measure a sample under different conditions, say, in a standard RTDC chip and then also in an MMM chip. For the measurement in the MMM chip, I would use a pressure pump instead of the syringe pumps, so the information about the pressure would not be in the .rtdc file, since it's not supported by Shape-In. I have written a little Python script that can communicate with the pressure pump and writes the pressure values together with time stamps in a text file, which is then stored together with the .rtdc files. I might also have to rearrange the position of the region of interest, so I might take a screenshot of the "prepare mode" in Shape-In where I can see the whole field of view of the camera and the position of the ROI within that field of view, in order to be able later where exactly in the chip I imaged the cells.

Could I actually also use Shape-Link to save the pressure value for each measurement directly in the .rtdc file? Probably not, but I could get the index of the current event and save it together with the current pressure of the pump in a csv file, right?

**Comment by B-Hartmann** [comment]
So for me, I would probably not need to have any special processing of different data types. Handling RTDC data and copying all other files in the same folder would be sufficient. But if I really wanted it, I could write my own recipe and have the functionality of different existing recipes combined into one, right?

**Comment by paulmueller** [comment]
Thanks. Regarding your Shape-Link question: In principle that should be possible, but it probably makes more sense to compare time stamps after the measurement to get/interpolate the pressure for each event (if that is needed).
